server:
  servlet:
    context-path: "/api"
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.json
  datasource:
    url: jdbc:mysql://localhost:3306/helospark_core
    username: helospark-development
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
article:
  list:
    pagesize: 10

security:
  jwt:
    secretKey: development_secret_key
    authentication:
      expirationTime: 864000000
    refresh:
      expirationTime: 31536000000
  image:
    secretKey: development_image_secret_key

gallery:
  thumbnail:
    width: 200
  large:
    width: 800
  notfound:
    url: /notfound.jpg

image:
  localfilesystem:
    basepath: /tmp/images